language: node_js

services:
  - docker

sudo: required

os:
  - linux
node_js:
  - '6'
script:
  - npm test -- --coverage



notifications:
  slack: leconseil:HXE2xW8zkscEYXCBWCHzmF0x

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker build -t picshape/picshape-front . ;
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push picshape/picshape-front;
    fi
